#!/usr/bin/env python3
"""Generate docs/REFERENCE.md — the human-browsable index of every skill, command,
agent, and hook — from the frontmatter itself, so it cannot drift from the territory.
check-scaffold regenerates and diffs it; edit frontmatter, never the output file.
Usage: python3 .claude/scripts/build-reference.py [output-path]"""

import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

ROOT = Path(__file__).resolve().parents[2]
CHASSIS = {"process", "governance", "testing", "memory", "wave-planning"}
TOOLS = {
    "env-uv",
    "tracking-mlflow",
    "tracking-wandb",
    "config-hydra",
    "config-omegaconf",
    "data-dvc",
    "hpo-optuna",
}


def frontmatter(path: Path) -> dict:
    m = re.match(r"(?s)\A---\n(.*?)\n---\n", path.read_text())
    if not m:
        return {}
    if yaml:
        try:
            return yaml.safe_load(m.group(1)) or {}
        except Exception:
            return {}
    d = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith(" "):
            k, _, v = line.partition(":")
            d[k.strip()] = v.strip()
    return d


def one_liner(desc: str, limit: int = 170) -> str:
    text = " ".join((desc or "").split())
    m = re.match(r"(.{20,}?[.!?])\s", text + " ")
    s = m.group(1) if m else text
    if len(s) > limit:
        s = s[: limit - 1].rsplit(" ", 1)[0] + "…"
    return s


def hook_line(path: Path) -> str:
    for line in path.read_text().splitlines()[1:6]:
        line = line.strip()
        if line.startswith("#") and len(line) > 4:
            return line.lstrip("# ").split(" — ", 1)[-1]
    return ""


def main() -> None:
    out_path = (
        Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "docs" / "REFERENCE.md"
    )
    settings = json.loads((ROOT / ".claude/settings.json").read_text())
    overrides = settings.get("skillOverrides", {})

    skills = {}
    for p in sorted((ROOT / ".claude/skills").glob("*/SKILL.md")):
        name = p.parent.name
        if name == "_example":
            continue
        skills[name] = one_liner(str(frontmatter(p).get("description", "")))

    lines = [
        "# Reference — every skill, command, agent, and hook",
        "",
        "> GENERATED by `.claude/scripts/build-reference.py` from the frontmatter — do not edit by",
        "> hand (check-scaffold fails when this file is stale; regenerate instead). One line per",
        "> component; the full depth lives in each component's own file.",
        "",
        "## Skills — chassis (always on)",
        "",
        "| Skill | What it carries |",
        "|---|---|",
    ]
    for n in sorted(skills):
        if n in CHASSIS:
            lines.append(f"| [`{n}`](../.claude/skills/{n}/SKILL.md) | {skills[n]} |")

    lines += [
        "",
        "## Skills — workflow (always on)",
        "",
        "| Skill | What it carries |",
        "|---|---|",
    ]
    for n in sorted(skills):
        if n not in CHASSIS and n not in overrides:
            lines.append(f"| [`{n}`](../.claude/skills/{n}/SKILL.md) | {skills[n]} |")

    lines += [
        "",
        "## Skills — gated (flipped by `/intake` via `skillOverrides`)",
        "",
        "| Skill | Kind | Default | What it carries |",
        "|---|---|---|---|",
    ]
    for n in sorted(overrides):
        if n not in skills:
            continue
        kind = "tool" if n in TOOLS else "lane"
        lines.append(
            f"| [`{n}`](../.claude/skills/{n}/SKILL.md) | {kind} | {overrides[n]} | {skills[n]} |"
        )

    lines += ["", "## Commands", "", "| Command | Does |", "|---|---|"]
    for p in sorted((ROOT / ".claude/commands").glob("*.md")):
        name = p.stem
        if name == "_TEMPLATE":
            continue
        lines.append(
            f"| [`/{name}`](../.claude/commands/{name}.md) | {one_liner(str(frontmatter(p).get('description', '')))} |"
        )

    lines += [
        "",
        "## Agents",
        "",
        "| Agent | Does | Tools | Preloaded skills |",
        "|---|---|---|---|",
    ]
    for p in sorted((ROOT / ".claude/agents").glob("*.md")):
        name = p.stem
        if name == "_TEMPLATE":
            continue
        fm = frontmatter(p)
        lines.append(
            f"| [`{name}`](../.claude/agents/{name}.md) | {one_liner(str(fm.get('description', '')))} "
            f"| {fm.get('tools', '')} | {fm.get('skills', '—')} |"
        )

    lines += [
        "",
        "## Hooks (wired in `settings.json`)",
        "",
        "| Hook | Event | Does |",
        "|---|---|---|",
    ]
    wiring = []
    for event, entries in settings.get("hooks", {}).items():
        for entry in entries:
            matcher = entry.get("matcher", "")
            for hook in entry.get("hooks", []):
                name = Path(hook["command"]).name
                ev = f"{event} · {matcher}" if matcher else event
                wiring.append((name, ev))
    for name, ev in sorted(wiring):
        lines.append(
            f"| [`{name}`](../.claude/hooks/{name}) | {ev} | {hook_line(ROOT / '.claude/hooks' / name)} |"
        )

    lines += [
        "",
        "Also: the policy canon in [`.claude/memory/policy/`](../.claude/memory/policy/), the live",
        "project state in [`.claude/memory/process/`](../.claude/memory/process/), and the process",
        "framework itself at [`PROCESS.md`](../PROCESS.md).",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path} ({len(skills)} skills)")


if __name__ == "__main__":
    main()
